### ISSUE TITLE
Thanks a lot for this + minor contribution to take into account shape manipulation

### ISSUE THREAD

**Issue by Mohus** [Ziv-Barber/officegen#100]
Hello, 

Thanks a lot for this work and for sharing it ! 

If I may add a suggestion, I found some difficulties while generating powerpoint shapes to tweak them like you would do it with the little yellow dot in screen.

By exploring the code I changed the genpptx.js file around line 916 to take into account the parameters of the shapes (file enclosed). 

Once again thanks again and I hope that I managed to contribute with a my little skill level

Regards
[genpptx.zip](https://github.com/Ziv-Barber/officegen/files/221825/genpptx.zip)

**Comment by Ziv-Barber** [comment]
Thanks Mohus!
