### ISSUE TITLE
Cannot find a way to define tmp folder.

### ISSUE THREAD

**Issue by Salketer** [Ziv-Barber/officegen#102]
Hello,

I'm trying to run officegen on windows (if it can help) and there is no c:/tmp folder by default. I was getting an error until I created that folder... I'd rather use a parameter somewhere to define the folder where I want officegen to store files.

This will come in necessary in production as I'm not willing to totally mount /tmp into a ramdisk.

**Comment by pietersv** [comment]
This was an old line in the module `lib/msexcel-builder`.  That module  is copied wholesale as code into officegen rather than require'd into the project.  A while I had updated `protobi/msexcel-builder` to use JS-Zip in memory only, eliminating dependency on file system.  Not sure if this pull request  has since been accepted into the root project.  Will need to look and see if `protobi/officegen` has this version or another.   If not a fix would be to copy in updated msexcel-builder.

**Comment by Salketer** [comment]
Hello pieter,

Thank you very much for your fast answer. It seems to me that this project
is shattered into a couple of fork pieces... Is there anyone actively
maintaining it? I am looking into a nice project that would heavily depend
on pptx generation and will certainly need to add features and debugs so I
am wondering if forking it and keeping my own copy would be better or if
there's an "official" fork.

Thanks for your input.
On May 3, 2016 17:52, "Pieter Sheth-Voss" <notifications@github.com> wrote:

This was an old line in the module lib/msexcel-builder. That module is
copied wholesale as code into officegen rather than require'd into the
project. A while I had updated protobi/msexcel-builder to use JS-Zip in
memory only, eliminating dependency on file system. Not sure if this pull
request has since been accepted into the root project. Will need to look
and see if protobi/officegen has this version or another. If not a fix
would be to copy in updated msexcel-builder.

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/Ziv-Barber/officegen/issues/102#issuecomment-216573877>

**Comment by pietersv** [comment]
@Salketer I believe officegen is stable, with occasional PRs accepted but not in stage of active or rapid development.  Let's connect privately on a clean-room JS library we've developed for reading-editing-generating PowerPoint in production at Protobi, not yet publicly released.

**Comment by Ziv-Barber** [comment]
I'm sorry that I was busy with another huge project. I'm going to continue improving Officegen. It's not a dead project.

**Comment by Ziv-Barber** [comment]
I added an option to set the temp folder.
But I'm going to change how the charts is working.
