### ISSUE TITLE
Error: ENOENT: no such file or directory, open 'c:\tmp\sample1.xlsx' when creating graph in pptx

### ISSUE THREAD

**Issue by Salketer** [Ziv-Barber/officegen#103]
Hello,

Using this code to add a chart to a slide produces the mentioned error.
```
slide.addChart({data: data, renderType: slide_definition.type});
slide.addText ( [
    { text: 'Hello ', options: { font_size: 56 } },
    { text: 'World!', options: { font_size: 56, font_face: 'Arial', color: 'ffff00' } }
], { cx: '75%', cy: 66, y: 150 } );
```
I do not understand where the "sample1.xlsx" is coming from...

**Comment by Mohus** [comment]
I got similar error while generating slides while keeping previous output open on my desktop. If I am not mistaken to create the charts in ppt the library stores the data in a temporary Excel file.

**Comment by japneet121** [comment]
I had the same issue.
For creating  charts the library uses a temporary excel file "sheet1" and it  will be created  at c:\tmp in your case. 
create a folder tmp in c drive and it will be work.

**Comment by Ziv-Barber** [comment]
It's related to the charts support. I need to work on it and I'm planing to do that in the next days.

**Comment by Ziv-Barber** [comment]
I added an option to set the temp folder.
But I'm going to change how the charts is working.

**Comment by pietersv** [comment]
I had revised https://github.com/chuanyi/msexcel-builder a while back to use JSZip  so that the charts generate the embedded Excel workbook in memory, eliminating dependency on the `/tmp` folder inherited from the @vtloc fork of the project.    This was submitted in pull request #83.

**Comment by florent-rivoire** [comment]
If someone got a similar error on **Mac OS X**, you should verify that you have the JDK installed (yes, java stuff for this nodejs module).
To be sure, execute `jar` in a shell, and check if you dont have a message telling you to install java.

The reason : the lib `msexcel-builder.js` uses the (external) binary `jar` to generate the .xlsx file that is (internally) used to store data from charts, cf source :
https://github.com/Ziv-Barber/officegen/blob/master/lib/msexcel-builder.js#L866-L873
And no error is triggered if the JDK is not installed.

**Comment by himanshushinde26** [comment]
@Salketer  How did you solve this problem?

**Comment by pietersv** [comment]
Try https://github.com/protobi/officegen
* The issue is that the PPTX charts generate embedded Excel workbooks. 
* The original vtloc branch used msexcel-builder to generate Excel not officegen
* That branch wrote to a /tmp file
* The /tmp directory can be assumed in linux/osx but may not exist on Windows or other OS
* This branch uses JSZip to generate the embedded Excel in memory

**Comment by himanshushinde26** [comment]
@pietersv It is working. Thanks a lot.

**Comment by Ziv-Barber** [comment]
You can also use the 'tempDir' settings when creating the document object.

**Comment by shobhitsharma** [comment]
@Ziv-Barber Could you please specify where to set this option. I'm using macOS, and it seems to created temps on project root. Which turns into ENOENT error.

**Comment by Ziv-Barber** [comment]
I'm in the process to merge https://github.com/protobi/officegen into my officegen so you can use native charts also with the normal officegen.
