### ISSUE TITLE
Pptx slide custom size

### ISSUE THREAD

**Issue by danmo** [Ziv-Barber/officegen#112]
Is there any way to change the size of a slide to some custom dimensions ?

**Comment by japneet121** [comment]
you have to customize genpptx.js file in lib folder 


you have to change the variables sldSZ    and type. to know different values of these variables  try with different ppt sizes and saving them as XML and then searching the value

**Comment by codecounselor** [comment]
would be great if this could be done via the API.  If not I will probably need to use another solution.  Would you accept a PR for adding width and aspect ratio options to the constructor?

**Comment by Ziv-Barber** [comment]
Version .0.4.2 allow you to do that:

pptx.setSlideSize ( cx, cy, type )

cx and cy = in pixels.
cx = horizontal side.
cy = vertical side.

the type parameter can be one of these:

'35mm'
'A3'
'A4'
'B4ISO'
'B4JIS'
'B5ISO'
'B5JIS'
'banner'
'custom'
'hagakiCard'
'ledger'
'letter'
'overhead'
'screen16x10'
'screen16x9'
'screen4x3'

At the time of writing this comment it's only available with the Github version but soon I'm going to release version 0.4.2 with many new features including this one.

**Comment by codecounselor** [comment]
awesome, thank you!

**Comment by danmo** [comment]
Thanks, that did it.
