### ISSUE TITLE
PowerPoint Repair File

### ISSUE THREAD

**Issue by heme** [Ziv-Barber/officegen#124]
The generated pptx files receive this error when opened...

> PowerPoint found a problem with the content in the file _______.pptx. PowerPoint can attempt to repair the file. If you trust the source of this file, click Repair.

Anyone else receiving this?

![powerpoint_repair](https://cloud.githubusercontent.com/assets/587462/17903772/532a2386-6932-11e6-9754-ce2222b1728a.png)

**Comment by Ziv-Barber** [comment]
heme, can you send an example code to create a pptx file that not working? What PowerPoint version are you trying to open the file with?

**Comment by heme** [comment]
This was being caused by an `.emf` image we were adding to the PowerPoint. The `.emf` was a very basic line drawing exported from Adobe Illustrator then added using `addImage`. I don't know if the problem was with the emf image or the way it is being added to the PowerPoint. Our solution was just to convert the `emf` to a `png`.

@Ziv-Barber Thanks for the fast response, and thanks for sharing all your work!
