### ISSUE TITLE
bar chart creation in ppt

### ISSUE THREAD

**Issue by RavikiranBaisani** [Ziv-Barber/officegen#130]
Error: ENOENT: no such file or directory, unlink 'D:\ppt\powerpoint\sample1.xlsx

Getting the above error while create a chart in ppt slide. Any clue?

**Comment by florent-rivoire** [comment]
It might be the same issue than issue #103

**Comment by Ziv-Barber** [comment]
Version 0.4.0 is out.

**Comment by 18876293672** [comment]
how to resove it ? @Ziv-Barber
