### ISSUE TITLE
ERROR while creating charts in ppt

### ISSUE THREAD

**Issue by RavikiranBaisani** [Ziv-Barber/officegen#131]
fs.js:758
  return binding.rmdir(pathModule._makeLong(path));
                 ^

Error: ENOTEMPTY: directory not empty, rmdir 'D:\ppt\powerpoint\4388803'
    at Error (native)
    at Object.fs.rmdirSync (fs.js:758:18)
    at Workbook.cancel (D:\ppt\powerpoint\node_modules\officegen\lib\msexcel-builder.js:877:17)

It's happening with msexcel-builder 
Any clue?

**Comment by Ziv-Barber** [comment]
Yes, sorry, working to merge the last changes in the PPT charts support into officegen.
Right now it do passing it without errors but it building XMLs with errors.
I'll continue to work on that to make it to work again. Sorry for this.

**Comment by Ziv-Barber** [comment]
Version 0.4.0 is out.
