### ISSUE TITLE
generate a document more than once

### ISSUE THREAD

**Issue by hdoedens** [Ziv-Barber/officegen#141]
I am using officegen from an Electron application. I want the user to be able to generate a document, review it, and while the application is still running, modify some input params and generate the document again. 
However the second and consecutive times aan error is thrown: `events.js:160 Uncaught Error: write after end`
How can I reset the document?
```
$scope.generate = function () {
    var officegen = require('officegen');
    var doc = officegen('pptx');
    $scope.liturgie.forEach(function (element) {
      element.documents.forEach(function (document) {
        makeSongSlide(doc, element.regel, document.verse, document.text)
      }, this);
    }, this);
    doc.generate(out, {
      'finalize': function (written) {
        console.log('Finish to create a PowerPoint file.\nTotal bytes created: ' + written + '\n');
      },
      'error': function (err) {
        console.log(err);
      }
    });
  }
```

**Comment by Ziv-Barber** [comment]
It's look like the problem is with your "out" stream.
You should pass a new output stream for each call to generate.

**Comment by hdoedens** [comment]
Wow, thanks @Ziv-Barber. I had tried many things, but apparently overlooked this one somehow...
