### ISSUE TITLE
Widescreen pptx generation resize object for normal size

### ISSUE THREAD

**Issue by vboiteau** [Ziv-Barber/officegen#142]
When I'm generating a pptx the output values relative to position and size are 0.75 times the expected values. if I apply a 1.333 modifier on all values relative to position and size, I get the expected output.

I'm setting the aspect ratio before creating slides and calling the generation task. I'm guessing that the resizing for the normal ratio 4/3 is done before the widescreen detection in the generation process, since (4/3) / (16/9) = 0.75.

**Comment by Ziv-Barber** [comment]
Try now with the last github version.

**Comment by vboiteau** [comment]
Yeap, works now.

Thanks and awesome module btw.
