### ISSUE TITLE
Unable to create more than one (1) table

### ISSUE THREAD

**Issue by tutnes** [Ziv-Barber/officegen#147]
Hi I have tried with both Powerpoint and Word (pptx and docx) but I am not able to create more than one table.
The below code is one example.
I have tried several different ways, but it seems like when I add a new table the table reference stays the same.

`for (let serviceID = 0; serviceID < d.services.length; serviceID++) {
		test[serviceID] = serverTableHeader;
		for (var serverID = 0; serverID < d.services[serviceID].servers.length; serverID++) { //d.services[serviceID].servers.length
			if (d.services[serviceID].servers[serverID].inBreach()) {
				test[serviceID].push([d.services[serviceID].servers[serverID].ID,
					helper.roundPrecise(d.services[serviceID].servers[serverID].availabilityTarget, 2),
					helper.roundPrecise(d.services[serviceID].servers[serverID].availability, 2),
					helper.roundPrecise(d.services[serviceID].servers[serverID].down, 2)
				]);
			}
		}`

**Comment by japneet121** [comment]
You can create different data arrays for different tables ,in this case it will create tables with different references. @tutnes
