### ISSUE TITLE
how to close the file system 

### ISSUE THREAD

**Issue by 17hz** [Ziv-Barber/officegen#169]
when i create the docx firstly ,it works good, but when i continue to create the second docx it will paste the first docx's content before the latest . I try to put "docx.generate ( out )"  to  "async.parallel()" body ,but it doesn't work,So it made me wonder 
@Ziv-Barber

**Comment by Ziv-Barber** [comment]
var docx = officegen ( 'docx' );

// ...

var file1 = fs.createWriteStream ( '1.docx' );

file1.on ( 'error', function ( err ) {
    console.log ( err );
});

file1.on ( 'close', function () {
    var file2 = fs.createWriteStream ( '2.docx' );

    file2.on ( 'error', function ( err ) {
        console.log ( err );
    });

    file2.on ( 'close', function () {
    });

    docx.generate ( out );
});

docx.generate ( out );

**Comment by iamjenmackle** [comment]
Ok but what if you are generating new files all the time? This solution only works if you create a couple of files but it's not scalable. I tried closing the writeStream but that didn't work either.
