### ISSUE TITLE
when use officegen to create a xlsx file, occure an open error 

### ISSUE THREAD

**Issue by AaronKim-CN** [Ziv-Barber/officegen#173]
I have use officegen to output a xlsx file. But when I want to open it, there will occur some error.  
Please see the file I have attached.

I have use this library before, So I have moved the officegen folder where in the Node_module from my old projects to new one. So the problem have resolved.  Is there any problem on new version? (0.4.4). Or other related library?

Following is my example code.
[Test.xlsx](https://github.com/Ziv-Barber/officegen/files/815596/Test.xlsx)

```
var officegen = require('officegen');
var xlsx = officegen ('xlsx');

[[some process]]

var out = fs.createWriteStream('alchemy_test_result.xlsx');
 xlsx.generate(out); 
```

**Comment by ArnaudNicklausAugure** [comment]
Also experienced the same issue.
Workaround: Set a column width.

**Comment by uforgetmenot** [comment]
@AaronKim-CN  The xml generated by the library has the same problem.

**Comment by AaronKim-CN** [comment]
@uforgetmenot Finally, I had change to the library exceljs. I can not solve this issue.

**Comment by reviewher** [comment]
The Error Log generated by Excel is surprisingly helpful here:

```
Repaired Part: /xl/worksheets/sheet1.xml with XML error.  System error: -2147418113. Line 2, column 303.
```

The relevant part of that XML is

```xml
<cols></cols>
------------^
```

According to the XML Schema from ECMA-376, there should be at least one `col` child element:

```xml
<complexType name="CT_Cols">
    <sequence>
       <element name="col" type="CT_Col" minOccurs="1" maxOccurs="unbounded"/>
    </sequence>
</complexType>
```

FWIW [js-xlsx](https://github.com/SheetJS/js-xlsx/blob/master/bits/67_wsxml.js#L321) omits the entire section if the writer does not expect to generate any column records.  That's probably what `officegen` should do.  I would guess that officegen eagerly writes `<cols>` without checking how many `<col>` records need to be generated.

**Comment by Ziv-Barber** [comment]
Thanks, I'll change it.

**Comment by Ziv-Barber** [comment]
Fixed in the last commit
