### ISSUE TITLE
PPT: addText breaks the export if passing null

### ISSUE THREAD

**Issue by namirsab** [Ziv-Barber/officegen#176]
### Observed
When adding `null` as a text, the ppt generator fails.
### Expected
Take null as an empty text
### Reproduce By
* Add null as a text
* Generate a powerpoint

### More info
https://github.com/Ziv-Barber/officegen/blob/master/lib/genpptx.js#L1288
That's the exact line that's causing the issue. It's checking if `typeof foo` is object, but `null` is also considered an object by `typeof`.

**Comment by Ziv-Barber** [comment]
Fixed in the last commit
