### ISSUE TITLE
Compatibility: Latest Keynote won't open officegen generated pptx files

### ISSUE THREAD

**Issue by eugeneware** [Ziv-Barber/officegen#18]
Hi, absolutely LOVE officegen. We'd love to use it to generate powerpoint slides in a new project that we're building.

However, there's a problem with the file format generated by pptx.

When I generate out the example pptx in the examples folder (or even just a basic single slide - see code below), and try to open it in the latest Keynote on Mac OS X I get the error: 

`“bad.pptx” can’t be opened.`

Ideally, rather than generate both keynote and pptx files, we could just generate a single pptx file and rely on keynote compatibility to work with both.

Here's the [bad.pptx](https://dl.dropboxusercontent.com/u/4763380/officegen/bad.pptx) that is generated that causes the issue.

When I open the `bad.pptx` in MS Powerpoint and save it back out as `good.pptx` here's what I get:

[good.pttx](https://dl.dropboxusercontent.com/u/4763380/officegen/good.pptx)

Here's the test js file that creates the bad.pptx:

``` js
var officegen = require('officegen');

var fs = require('fs');
var path = require('path');

var pptx = officegen ( 'pptx' );

var slide;
var pObj;

pptx.on ( 'finalize', function ( written ) {
            console.log ( 'Finish to create a PowerPoint file.\nTotal bytes created: ' + written + '\n' );
        });

pptx.on ( 'error', function ( err ) {
            console.log ( err );
        });

pptx.setDocTitle ( 'Sample PPTX Document' );

// Let's create a new slide:
slide = pptx.makeNewSlide ();

slide.name = 'The first slide!';

// Change the background color:
slide.back = '000000';

// Declare the default color to use on this slide:
slide.color = 'ffffff';

// Basic way to add text string:
slide.addText ( 'Created using Officegen version ' + officegen.version );
slide.addText ( 'Fast position', 0, 20 );
slide.addText ( 'Full line', 0, 40, '100%', 20 );

var out = fs.createWriteStream ( 'bad.pptx' );

out.on ( 'error', function ( err ) {
    console.log ( err );
});

pptx.generate ( out );

```

**Comment by keithmo** [comment]
I have a fix for this issue; it's a relatively simple change in genpptx.js. https://github.com/Ziv-Barber/officegen/pull/51

**Comment by mlolson** [comment]
Keynote crashes when I try to open the pptx generated by the example script. The pptx appears to convert successfully then keynote crashes before opening the file.

**Comment by dasblitz** [comment]
I seem to experience this issue as well running officegen 2.14.0 and Keynote 6.5.3. If there's any way I can help, providing logs etc. let me know.

**Comment by pietersv** [comment]
@dasblitz @mlolson 
* Is the issue unique to Keynote?  Can you open the file without issue in PowerPoint and/or LibreOffice?
* Can the issue be localized to specific content, or does even the smallest file crash in Keynote?  If a minimal file works, can you isolate the problem content?
* If the file opens fine in PowerPoint but crashes Keynote, can you save it to a new  file from within PowerPoint and open the new saved file within Keynote?

**Comment by dasblitz** [comment]
I just downloaded Open Office and the generated pptx works. I've minimized the code to the code below basically creating an empty pptx. The generated pptx file opens in Open Office but Keynote immediately shows 'Can't open file'. If I save the file from Open Office to a .ppt file the ppt file opens in Keynote.

    var pptx = officegen ( 'pptx' );
    pptx.on ( 'finalize', function ( written ) {
        // ... 
        console.log ( 'Finish to create the surprise PowerPoint stream and send it to ' + response.post.name + '.\nTotal bytes created: ' + written + '\n' );
    });
     
    pptx.on ( 'error', function ( err ) {
        // ...
        console.log ( err );
    });
     
    pptx.generate ( response );

**Comment by dasblitz** [comment]
To add, open office has no option for saving to .pptx just ppt. I''l have to wait until monday before I have access to a macbook with powerpoint installed.

**Comment by dasblitz** [comment]
So I just downloaded LibreOffice as well. Turns out that if I create a new slideshow in Libre Office and save it as a .pptx weather it's the Microsoft PowerPoint 2007-2013 XML (.pptx) or the Open Office XML Presentation (.pptx) both of them won't open in Keynote ("file.pptx can't be opened"). 

If I create a pptx file from Keynote and unzip the file to view the xml. The [Content_Types].xml differs quite a lot from the [Content_Types].xml that officegen generates:

https://www.dropbox.com/s/tf3hlio1lwzq1m0/diff.jpg?dl=0

So it seems this is more a Keynote problem than an officegen 'bug'.

**Comment by pietersv** [comment]
Awesome sleuthing.  Concur it's probably specific to Keynote. I've been surprised by how brittle PowerPoint and Keynote are to even the slightest deviation from expected content.

**Comment by dasblitz** [comment]
@pietersv @Ziv-Barber 

Well this was bugging me so I dug a little deeper. The problem seems to come from the generated file 

ppt/_rels/presentation.xml.res

Compared to a pptx generated with MS Powerpoint. It's missing the presProps, viewProps, theme1 and tableStyles relationship definitions. 

The pptx seems to open in Keynote if I replace the codeblock in genpptx.js at line 1164 with the following:

    gen_private.type.msoffice.rels_app.push (
		{
			type: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideMaster',
			target: 'slideMasters/slideMaster1.xml',
			clear: 'type'
		}, {
			type: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/slide',
			target: 'slides/slide1.xml'
		}, {
			type: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/presProps',
			target: 'presProps.xml'
		} , {
			type: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/viewProps',
			target: 'viewProps.xml'
		}, {
			type: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/theme',
			target: 'theme/theme1.xml'
		}, {
			type: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/tableStyles',
			target: 'tableStyles.xml'
		}
	);

Note that the order of slideMaster1 and slide1 is important. If you put the slide1 object in the end it doesn't work.

I can make a pull request for this, but it feels a little hacky due to me semi-understanding the whole pptx thing, so I'm not sure weather this could break anything.

**Comment by dasblitz** [comment]
Fuck me, I just forked the repository and saw the code on git already had this fixed. Now I also see @keithmo had a similar fix. I never looked in to it because it seemed it was fixed. It's just that the npm module still has the old code. Well at least now I know something more about pptx.
