### ISSUE TITLE
Table, 1 row to fit in all columns (Table on docx)

### ISSUE THREAD

**Issue by johnfrades** [Ziv-Barber/officegen#181]
Hi, i just want to implement a 1 row that will populate on all column

![image](https://cloud.githubusercontent.com/assets/20201069/24903177/bb7ae95a-1f00-11e7-9ea8-237decf29ee4.png)

similar to this one that i've uploaded. Is this achievable using this officegen?

Thank you!

**Comment by conceptualspace** [comment]
yes i believe you're looking for `opts: {gridSpan: 2}`

https://github.com/Ziv-Barber/officegen/blob/master/examples/make_table_cell_span.js

**Comment by johnfrades** [comment]
Cheers!
