### ISSUE TITLE
Import existing Office documents?

### ISSUE THREAD

**Issue by deed02392** [Ziv-Barber/officegen#187]
Is it possible to import existing office documents and access the equivalent JSON that would be used to generate that document?

**Comment by Ziv-Barber** [comment]
Not yet but there's a plan for that in the near future.

**Comment by Rishav12345** [comment]
Will this also allow importing/adding/embedding a pdf document as well as on OLE object into a slide?

**Comment by deed02392** [comment]
@Ziv-Barber Any update? :)

**Comment by Cxz-web** [comment]
> Not yet but there's a plan for that in the near future (for importing existing files).

Hello, can I import the PPT now?

**Comment by Ziv-Barber** [comment]
Duplicate #33
