### ISSUE TITLE
Docx Templates/Content Replace

### ISSUE THREAD

**Issue by bencevans** [Ziv-Barber/officegen#19]
Hi,

This module looks great, I've had a browse through but not found anything. I'm looking to import a doc/docx file and replace conbtent with new content e.g '{{title}}' with 'My New Title'. Much like handlebars or other templating engines.

Is this possible with your module?

Cheers,
Ben.

**Comment by jfairley** [comment]
I came across this repository (https://github.com/edi9999/docxtemplater) recently. It _only_ does templating. Ultimately, I wish it did more, so I'll probably continue using officegen, but maybe someone will find it useful.

**Comment by bencevans** [comment]
@jfairley Thanks for the tip!

**Comment by jaSunny** [comment]
👍 same for pptx so that a slide can serve as template!

**Comment by Ziv-Barber** [comment]
see #33
