### ISSUE TITLE
path is not defined

### ISSUE THREAD

**Issue by meiduo** [Ziv-Barber/officegen#191]
When I use docx addImage，the code throw exception: **`path is not defined`**
The reason is 
![image](https://cloud.githubusercontent.com/assets/7929293/26048782/224a34d4-398b-11e7-8872-413b81e54785.png)

Now my solution is defined gloab.path=require('path') in my code
but I think this is not a good solution

/cc @shawyeok

**Comment by edencorbin** [comment]
Same issue, and the solution worked for me too, I also agree this is not a good long term solution.

**Comment by jnstyle** [comment]
me to

**Comment by Corvusnest** [comment]
I added "var path  = require('path');" just before "var image_ext = path.extname ( image_path );"
It works fine for me.

**Comment by OctoberCity** [comment]
same question，Although I added "path", it does not solve the problem of adding gif images.How do you solve it?How do you solve it? This is a troublesome thing.

**Comment by Ziv-Barber** [comment]
Fixed
