### ISSUE TITLE
How to put a Tab Indentation

### ISSUE THREAD

**Issue by johnfrades** [Ziv-Barber/officegen#201]
Hello, i just want to ask how to put a tab indentation. Because as of now i'm using SPACEBAR as my spacing, but that doesn't get the job done.
<img width="682" alt="screen shot 2017-06-16 at 12 49 31" src="https://user-images.githubusercontent.com/20201069/27207342-45714f22-5292-11e7-987f-0a458fa6afac.png">
This is the one that im trying to achieve. The spacing between the Date and the Work Position

**Comment by Jodge** [comment]
@johnfrades how did you fix this?

**Comment by 159159951** [comment]
I want to add \t (tab) but currently seem like does not support.
Please up vote enhancement.
