### ISSUE TITLE
For loop & If and Else statement inside Table (Generating Word)

### ISSUE THREAD

**Issue by johnfrades** [Ziv-Barber/officegen#204]
Have you tried doing a for loop / if & else statement when generating a table on word? Because on my end i can't make it work. Here's the code

```
var data = {
    date: "Aug 2016 – Current",
    position: "Career Services Manager",
    place: "University college",
    responsibilities: [
        "The responsibility is something to think aboutaboutaboutaboutaboutaboutabout",
        "The happening has happened bro!"
    ]
}


var table = [
    [{
        val: ""
    },{
        val: ""
    },{
        val: ""
    }],
    [data.date, {val: data.position, opts: {gridSpan: 2, b: true}}],
    [data.date, {val: data.place, opts: {gridSpan: 2}}],
    data.responsibilities.forEach(function(resp){
        ["", {val: String.fromCharCode( 8226 ) + resp, opts: {gridSpan: 2}}]
    })
];
```

It gives me an error of
```
          row.map(function(cell) {
             ^

TypeError: Cannot read property 'map' of undefined
```

When i try to do an if & else statement it is also giving me an error.

Do you know how to generate a table with a dynamic data?

**Comment by varsha2409** [comment]
You can do something like this:

var table = [
    [{
        val: ""
    },{
        val: ""
    },{
        val: ""
    }],
    [data.date, {val: data.position, opts: {gridSpan: 2, b: true}}],
    [data.date, {val: data.place, opts: {gridSpan: 2}}]
];

data.responsibilities.forEach(function(resp){
        table.push(["", {val: String.fromCharCode( 8226 ) + resp, opts: {gridSpan: 2}}])
    })

**Comment by johnfrades** [comment]
Thank you so much!!
