### ISSUE TITLE
Left and Right Aligned Header/Footer content and Images

### ISSUE THREAD

**Issue by edencorbin** [Ziv-Barber/officegen#215]
I'm looking to do left and right aligned header/footer images. From the docs/issues it looks like left and right aligned are not possible as tables are not supported in headers? Also, I see another open issue (also confirmed in my own testing) that adding images does not work on headers/footers. Generally can what I'm looking to achieve be done with officegen currently, and if not with the header directly, is there a workaround? If the issue is known can you point me where I might look at the source to do a PR to add this functionality?

**Comment by Ziv-Barber** [comment]
Duplicate #179
