### ISSUE TITLE
Unable to addImage to header in docx. Unable to change pageMargins in docx. 

### ISSUE THREAD

**Issue by srikanthdarmapuri** [Ziv-Barber/officegen#235]
1.
var header = docx.getHeader ().createP ();
header.addImage(path.resolve(__dirname, 'header.png' ));
<img width="660" alt="screen shot 2017-12-08 at 1 50 48 pm" src="https://user-images.githubusercontent.com/6670995/33780462-d9b3beac-dc1e-11e7-9908-4719230edc59.png">

=======
//npm installing v 0.4.5 which doesn't support this functionality  
2.
var docx = officegen ({
	type: 'docx',
	orientation: 'portrait',
	pageMargins: { top: 1600, left: 1200, bottom: 1200, right: 1200 }
	// The theme support is NOT working yet...
	// themeXml: themeXml
});

**Comment by Joban1992** [comment]
I also faced this problem. But, as of now mages are not supported in header and footer.

**Comment by Ziv-Barber** [comment]
Duplicate #179
