### ISSUE TITLE
how to insert indent before each para of docx? 

### ISSUE THREAD

**Issue by linYeeTracy** [Ziv-Barber/officegen#237]
hey dude, i'm excited to find this package, then i still have question:
1. how can i insert indent before each para of docx? i try to set the param 'indexLevel', but it doesn't work
2. when i  use addLineBreak(), to enter the line, then i find some line Interval  been insert, so i wanna know that can i pass some params to delete the interval ?

thanks

**Comment by bkylerussell** [comment]
I ran into the same need and submitted PR #262 to add very basic indent support, which was enough for my needs.  It looks like there are some options to customize even further though if there's enough interest (http://officeopenxml.com/WPindentation.php).
