### ISSUE TITLE
pageMargins is not work in docx

### ISSUE THREAD

**Issue by aowakennomai** [Ziv-Barber/officegen#244]
in sample file 'make_docx.js', 
`pageMargins: { top: 1000, left: 1000, bottom: 1000, right: 1000 }` is used as options while creating docx obj,
but in created docx file, it is not applied.

look into 'gendocx.js', it seems be hard coded as below at line 435...(i'm not sure)
`				outString +=
					'<w:sectPr w:rsidR="00A02F19" w:rsidSect="00897086">' +
					(docxData.secPrExtra ? docxData.secPrExtra : '') +
					'<w:pgSz w:w="15840" w:h="12240" w:orient="landscape"/>' +
					'<w:pgMar w:top="1800" w:right="1440" w:bottom="1800" w:left="1440" w:header="720" w:footer="720" w:gutter="0"/>' +
					'<w:cols w:space="720"/>' +
					'<w:docGrid w:linePitch="360"/>' +
					'</w:sectPr>';`

**Comment by tidusx18** [comment]
Having the same issue. Page margins options not being applied to the created document.

**Comment by uxal** [comment]
Check out my fork, setting the margins works now

**Comment by codecounselor** [comment]
Looks like master has this patch in it, any intention of publishing a new version to NPM?

**Comment by Ziv-Barber** [comment]
Implemented in the latest npm versions
