### ISSUE TITLE
how to define docx file's layout size

### ISSUE THREAD

**Issue by aowakennomai** [Ziv-Barber/officegen#245]
How to define docx file's layout size like 'A4' or 'B5' or something else which is predefined in MS-Word?
Currently I get predefined 'Letter' layout as default.

**Comment by uxal** [comment]
@aowakennomai Check out the fork I did, I've added A4 support because it's the only one I needed in my project

**Comment by Ziv-Barber** [comment]
I'm check your fork to add it into the official code
