### ISSUE TITLE
ppt addTable options not working

### ISSUE THREAD

**Issue by srikanthdarmapuri** [Ziv-Barber/officegen#246]
slide.addTable(rows, { x: 588, y: 210});
I have provided x, y positions but table is added at 0,0 positions in the slide.

**Comment by jmetric** [comment]
Hope you have already figured this out, but I am assuming you are treating 588 and 210 as pixels. Have you tried converting to EMUs?  Math.round(588 * 9525)

**Comment by rishabh6072** [comment]
This worked but after converting into EMUs I'm getting different positions on different devices (As EMU is dependent on the resolution of the device, I guess).
