### ISSUE TITLE
officegen calling finalize event before document is flushed to disk

### ISSUE THREAD

**Issue by spollack** [Ziv-Barber/officegen#26]
We are seeing consistent behavior where when officegen raises the finalize event, the file is not yet flushed to disk. For example, the finalize event will say the pptx is 745239 bytes, but if i do fs.stat on the file immediately afterwards, the size is 741962.  a few milliseconds later, the file size is as expected. This is using officegen 0.2.8 on node 0.10.28. We do not see this behavior (or at least not consistently) on node 0.8.26. 

our generation code looks like this: 

```
            var out = fs.createWriteStream(paths.pptxFilePath);
            out.on('error', function (error) {
                onCompletion(error, null);
            });

            pptx.generate(out, {
                error: function (error) {
                    onCompletion(error, null);
                },
                finalize: function (bytesWritten) {
                    onCompletion(null, bytesWritten);
                }
            });

```

Do we need to do something different to know when it is available on disk? For now, i'm calling fs.stat in a loop with a small delay until the file sizes match (uggh).

**Comment by scorpwarp23** [comment]
@Ziv-Barber I'm having the same issue on node v0.10.38. Any updates?

**Comment by JZiebikiewicz** [comment]
Ooops, I've got the same problem. File is created on disk (0kb), finalize event is fired and then file is being saved (slowly increases its size). Node v6.9.5, Officegen v0.4.3

**Comment by FrancoisBeaune** [comment]
Encountering this problem as well, using node.js v6.10.

**Comment by woosungchu** [comment]
Same problem 
Node v.10.15.3

```
console.log(1)
docx.generate(out, {
            error: function (error) {
                console.log('error');
                console.log(error);
            },
            finalize: function (bytesWritten) {
              console.log('bytesWritten');
              console.log(bytesWritten);
            }
        });
console.log(2)
```

Output
```
1
bytesWritten
0
2
```

but file generated well without any error

**Comment by thearpist123** [comment]
same error. My workaround is using the WriteStream event 'finish' instead. E.g.
```javascript
docx.generate(out, {
  error: function (error) {
      console.log('error');
      console.log(error);
    },
    finalize: function (bytesWritten) {
      console.log('bytesWritten');
      console.log(bytesWritten);
    }
});
```
becomes
```javascript
out.on('error', (error) => {
  console.log('error');
  console.log(error);
});
out.on('finish', () => {
  console.log('bytesWritten');
  console.log(out.bytesWritten);
});
docx.generate(out);
```
