### ISSUE TITLE
How to generate two columns page in docx?

### ISSUE THREAD

**Issue by naveedaheer** [Ziv-Barber/officegen#272]
Can we generate a docx that should be **two columns layout**?

**Comment by OctoberCity** [comment]
I am trying to compare xml files, trying to find a solution

**Comment by naveedaheer** [comment]
I got the solution.

**Comment by naveedaheer** [comment]
In node_modules/lib/gendocx.js
					```
outString +=
						'<w:sectPr w:rsidR="00A02F19" w:rsidSect="00897086">' +
						(docxData.secPrExtra ? docxData.secPrExtra : '') +
						'<w:pgSz w:w="15840" w:h="12240" w:orient="landscape"/>' +
						'<w:pgMar w:top="1800" w:right="1440" w:bottom="1800" w:left="1440" w:header="720" w:footer="720" w:gutter="0"/>' +
						'<w:cols w:space="720"/>' +
						'<w:docGrid w:linePitch="360"/>' +
						'</w:sectPr>';
```
I replaced
`'<w:cols w:num="2"  w:space="720"/>'`

**Comment by OctoberCity** [comment]
good job!!!1

**Comment by OctoberCity** [comment]
@naveedaheer My business is troublesome, I have to use other methods, such as html conversion to docx, I think it will be more effective

**Comment by Jodge** [comment]
@naveedaheer so how do you end up passing data to the two columns using?
```js
const pObj = docx.createP();
```
