### ISSUE TITLE
generate a word document with a header and two column layout with a border in the middle

### ISSUE THREAD

**Issue by cultulhul** [Ziv-Barber/officegen#280]
is it possible to generate a document like this
https://www.scribd.com/document/391754619/Example

**Comment by Ziv-Barber** [comment]
Can you please upload the example document to gdrive or somewhere that I can download it without registering to anything? thanks

**Comment by OctoberCity** [comment]
https://github.com/Ziv-Barber/officegen/issues/272
you can try it

**Comment by Ziv-Barber** [comment]
Columns been implemented in version 0.6.3 (right now the dev branch but soon also in the master branch and npm)
