### ISSUE TITLE
How to create heading formats like h1?

### ISSUE THREAD

**Issue by MidaAiZ** [Ziv-Barber/officegen#282]
How can I  create heading formats like h1 h2 h3... ?  I have tried like this, but it doesn't work.
```js
  p = docx.createP();
  p.addText('test heading1 format');
  p.options.pStyleDef = 'Heading1'
```
It looks like this when converted into xml code in document.xml:
```xml
  <w:p w:rsidR="00A77427" w:rsidRDefault="007F1D13">
      <w:pPr><w:pStyle w:val="Heading1"/></w:pPr>
      <w:r>
        <w:t>test H1 format</w:t>
      </w:r>
   </w:p>
```

The xml code below is original code  generated by Microsoft Word in document.xml. it uses 'Heading1' property to create format H1, and it works well. I can not figure out why. As I see, they have the same tag or property;
```xml
<w:p w14:paraId="035E4301" w14:textId="77777777" w:rsidR="00161C7E" w:rsidRDefault="00AC5C69" w:rsidP="00AC5C69">
      <w:pPr><w:pStyle w:val="Heading1"/>
        <w:rPr><w:rFonts w:hint="eastAsia"/><w:lang w:eastAsia="zh-CN"/></w:rPr>
      </w:pPr>
      <w:r>
        <w:rPr><w:lang w:eastAsia="zh-CN"/></w:rPr>
        <w:t>T</w:t>
      </w:r>
      <w:r>
        <w:rPr><w:rFonts w:hint="eastAsia"/><w:lang w:eastAsia="zh-CN"/></w:rPr>
        <w:t>est H1 format</w:t>
      </w:r><w:bookmarkStart w:id="0" w:name="_GoBack"/><w:bookmarkEnd w:id="0"/>
</w:p>
```
![image](https://user-images.githubusercontent.com/20530529/47955294-e0a68080-dfd0-11e8-85a7-c7f53d802ff4.png)

**Comment by MidaAiZ** [comment]
Hello @Ziv-Barber , could you please help me? I found it may be a bug caused by missing styles.

**Comment by colinjeanne** [comment]
You need to add your own stylesheet XML. This was implemented in https://github.com/Ziv-Barber/officegen/pull/259.
