### ISSUE TITLE
Import existing Office documents?

### ISSUE THREAD

**Issue by Cxz-web** [Ziv-Barber/officegen#289]
### Environment

1. `node -v`: [fill]
1. `npm -v`: [fill]
1. `npm ls officegen`: [fill]
1. Operating system: [fill]
1. Microsoft Office version: [fill]
1. Problem with Powerpoint, Excel or Word document: [fill]

### Steps to Reproduce

[fill]

### Expected Behavior

[fill]

### Actual Behavior

[fill]

--- 

An example code will be the best.
The fastest (and the most fun) way to resolve the issue is to submit a pull-request yourself.

**Comment by Ziv-Barber** [comment]
It's not possible yet, sorry.
I'm thinking how to add this feature.

Ziv

**Comment by Cxz-web** [comment]
@Ziv-Barber  Thank you for your answer.
