### ISSUE TITLE
Specify width and height of PowerPoint slides for non standard sizes

### ISSUE THREAD

**Issue by deradam** [Ziv-Barber/officegen#29]
In PowerPoint you can specify the format of the paper and the size of the slides. From what I see in the API, this is currently not possible. Would be nice, if this could be passed as an option parameter.

**Comment by amorri40** [comment]
This would be a great feature, I'll try and see if I can find any clues for how to implement it.

**Comment by Ziv-Barber** [comment]
I'll check that. It should be simple to implement.

On Mon, Jan 12, 2015 at 4:48 PM, Alasdair Morrison <notifications@github.com

**Comment by joadr** [comment]
was this finally implemented? I can't find anything in the docs or in the code :/

**Comment by Zignd** [comment]
I'd like to see this feature, please.

**Comment by legraphista** [comment]
+1 for this feature

**Comment by legraphista** [comment]
Never mind, it's here: 
https://github.com/Ziv-Barber/officegen/blob/master/lib/pptxplg-widescreen.js#L47-L83
https://github.com/Ziv-Barber/officegen/blob/master/lib/pptxplg-widescreen.js#L85-L88

So you just have to call: 
`pptxDoc.setSlideSize(x, y);` if you want specific sizes.

**Comment by mvgalle** [comment]
thanks @legraphista . The following worked great for me and I was able to set the pptx to widescreen:  

```
var pptx = officegen('pptx');
pptx.setSlideSize(1920, 1080);

```
