### ISSUE TITLE
[QUESTION] How to render XML without using the application

### ISSUE THREAD

**Issue by donpinkus** [Ziv-Barber/officegen#294]
Is it possible to render the XML / document generated by `officegen` in a browser or without using the Microsoft application?

**Comment by Ziv-Barber** [comment]
officengen is NOT using Microsoft Office.
This code is full standalone code that is not depending on any Microsoft code or app!
It's working on any environment that supporting node.js
Right now it's not working in the browser so it's a backend only BUT I'm working on re-designing it to support also working in the browser.
