### ISSUE TITLE
Superscript/subscript

### ISSUE THREAD

**Issue by styts** [Ziv-Barber/officegen#299]
Hi,

Could you please provide support for subscript/superscript for docx files?

> <w:r w:rsidRPr="000E3A17">
>   <w:rPr>
>     <w:vertAlign w:val="superscript" /></w:rPr>
>   <w:t>this is a superscript</w:t>
> </w:r>

Something like `pObj.addText('super', { superscript: true })`.

**Comment by Ziv-Barber** [comment]
OK, this is easy. You'll get it in the next version that I'm going to release in the next days.

Ziv

**Comment by Ziv-Barber** [comment]
Already implemented for the next release.
If you really need it now, you can find it in the 'dev' branch.

**Comment by styts** [comment]
Thank you! I didn't expect it to go so quick, but because it was a dealbreaker I ended up using a competing library that already had this feature: `docx`.

**Comment by Ziv-Barber** [comment]
Added in 0.5.0 now out.
