### ISSUE TITLE
Could you tell me How to use it?

### ISSUE THREAD

**Issue by 18876293672** [Ziv-Barber/officegen#305]
### Environment

1. `node -v`: [fill]
1. `npm -v`: [fill]
1. `npm ls officegen`: [fill]
1. Operating system: [fill]
1. Microsoft Office version: [fill]
1. Problem with Powerpoint, Excel or Word document: [fill]

### Steps to Reproduce

[fill]

### Expected Behavior

[fill]

### Actual Behavior

[fill]

--- 

An example code will be the best.
The fastest (and the most fun) way to resolve the issue is to submit a pull-request yourself.

**Comment by Ziv-Barber** [comment]
Please refer to the documentation:

https://github.com/Ziv-Barber/officegen/blob/master/manual/README.md
