### ISSUE TITLE
How can I open the document right after generate

### ISSUE THREAD

**Issue by woosungchu** [Ziv-Barber/officegen#307]
### Environment

1. `node -v`: [v10.15.3]
1. `npm -v`: [6.4.1]
1. `npm ls officegen`: [officegen@0.5.2]
1. Operating system: [Window]
1. Microsoft Office version: [fill]
1. Problem with Powerpoint, Excel or Word document: [fill]

```
docx.generate(out, {
            finalize: function (bytesWritten) {
              console.log(bytesWritten); // it returns 0
              exec(docName); // it can't open the document
            }
        });
```
the document was successfully generated, but this can't open it

I know docx.generate() function is async method, but how can I open it
Doesn't docx.generate.finalize callback function?

* sorry for my bad english

**Comment by Jodge** [comment]
Paste the whole code here so someone can understand, the information above is scanty

**Comment by Ziv-Barber** [comment]
The right way to do it (and I need to add it to the documentation):

    var out = fs.createWriteStream(path.join(outDir, 'example.pptx'))

    out.on('error', function(err) {
        console.log(err)
    })

    out.on('finish', function(err) {
        // This is the real finish in case of creating a document file.
     })

     pptx.generate(out)

**Comment by woosungchu** [comment]
It works !!
```
out.on('finish', function(err) {
    // This is the real finish in case of creating a document file.
 })
```

Thank you for reply, Ziv-Barber
