### ISSUE TITLE
Words in Arabic are Mirrored

### ISSUE THREAD

**Issue by Ahmad-G-Mustafa** [Ziv-Barber/officegen#317]
### Environment

1. `node -v`: [fill]
1. `npm -v`: [fill]
1. `npm ls officegen`: [fill]
1. Operating system: [fill]
1. Microsoft Office version: [fill]
1. Problem with Powerpoint, Excel or Word document: [fill]

### Steps to Reproduce

[fill]

### Expected Behavior

[fill]

### Actual Behavior

[fill]

--- 

An example code will be the best.
The fastest (and the most fun) way to resolve the issue is to submit a pull-request yourself.

**Comment by Ziv-Barber** [comment]
I'll fix it for the next release.

**Comment by Ziv-Barber** [comment]
@Ahmad-G-Mustafa
You can also make the paragraph rtl and it'll work for you:

docx.createP({ rtl: true })

Then anything inside it will be displayed without mirroring the words.

**Comment by Ziv-Barber** [comment]
@Ahmad-G-Mustafa 
Anyway, I'll add a full fix.
