### ISSUE TITLE
Feature request: ability to specify list level/depth for Docx

### ISSUE THREAD

**Issue by mikeappell** [Ziv-Barber/officegen#321]
OfficeOpenXML allows for the specification of list level, e.g. nested lists: http://officeopenxml.com/WPnumbering.php

It would be great if there were a way to specify this when using the `createListOfNumbers` and  `createListOfDots` methods.

It would also be very useful if this caused the numbering/bullet style to change the way it does by default in Word, e.g. the first level of depth uses numbers, the second letters, the third `i / ii / iii` etc. Even cooler would be if we could choose the numbering/bullet style ourselves, though the default is just fine imo.

**Comment by Karanpreettoor** [comment]
Created [pull request](https://github.com/Ziv-Barber/officegen/pull/328) for this feature.

**Comment by mikeappell** [comment]
Hey Ziv! Sorry to be a pain – I know this PR was merged into your dev branch, but I was wondering if you had any idea when you might feel comfortable releasing it into master.

**Comment by hannojg** [comment]
Still wondering

**Comment by mikeappell** [comment]
This is working now (and working awesomely)! I'm gonna close this issue, thanks a ton Ziv.
