### ISSUE TITLE
Feature Request: ability to write to multiple columns

### ISSUE THREAD

**Issue by mikeappell** [Ziv-Barber/officegen#325]
OfficeOpenXML allows for specifying multiple columns when creating a document:

http://officeopenxml.com/WPsectionCols.php

This would be very useful for users who might be creating legal documents intended for courts, as those sometimes have very specific formatting requirements (often including columns.)

Also, Word has a "line between" option which creates a vertical divider between columns, which is going to be what most legal documents require.

**Comment by Ziv-Barber** [comment]
OK. I'll add it for version 0.6.2. The next version (0.6.1) will be more focus in PowerPoint features.
Version 0.6.1 will be out in the next days and I can add the Word features next week.

**Comment by mikeappell** [comment]
That's great to hear – thanks for the update.

**Comment by Ziv-Barber** [comment]
@mikeappell It's now available in the dev branch and soon it'll be part of officegen 0.6.3 (in the next days).

To use it:

    let docx = officegen({
        type: 'docx', // We want to create a Microsoft Word document.
        ... // Extra options goes here.
        columns: 2 // Or you can put here 3, 4, 5, ...       
    })
