### ISSUE TITLE
Creating bullet lists

### ISSUE THREAD

**Issue by samlobel** [Ziv-Barber/officegen#36]
The createListOfDots and CreateListOfNumbers doesn't really do anything for me. I assume it's supposed to make bullet-point formatting, but even when I create the sample doc, it just appears as new lines (no bullets or numbers). Is this a well-known problem? Is there a different way to create bullet points?

Attached is the bottom of the sample doc. Is that how it's supposed to look?
![screenshot from 2014-11-03 13 09 10](https://cloud.githubusercontent.com/assets/6496631/4887435/9089bb34-6384-11e4-8f22-ad6587fed69d.png)

**Comment by Verikon** [comment]
They way I dealt with this;

var bulletpoints = [ 'some key point', 'some other keypoint' ];

var bulletedString = bulletpoints.reduce( function( str, bulletpoint ) { 
  str += String.fromCharCode( 8226 ) + '  ' + bulletpoint + '\n\r';
  return str;
}, '');

slide.addText( bulletedString );

**Comment by Ziv-Barber** [comment]
#151
