### ISSUE TITLE
The text without space will not appear in docx

### ISSUE THREAD

**Issue by ppn029012** [Ziv-Barber/officegen#47]
In Node 10.28, and LibreOffice

Nothing appear in docx without space after the words.

```
var pObj = docx.createP();
pObj.addText('Hello,World');
```

but it works like

```
var pObj = docx.createP();
pObj.addText('Hello,World ');
```

Do I have to add space?

**Comment by protobi** [comment]
Confirm as issue.

**Comment by protobi** [comment]
Resolved in https://github.com/Ziv-Barber/officegen/pull/49
