### ISSUE TITLE
Officegen 0.2.7 never finalizes in Node 0.8

### ISSUE THREAD

**Issue by dmgreene** [Ziv-Barber/officegen#53]
OfficeGen prompts the user to start downloading the file as soon as docx.generate(res) is hit, however, it never finishes creating the file. In fact, it never even hits the callback of the finalize event (as shown below). Which makes me wonder... why does OfficeGen prompt the user before the file is built?  And can we circumvent that by not sending anything to the user until the file is built?

```
var docx = officegen('docx');
// Here I call docx.createP().addText("foo bar") about 300 times
docx.on ( 'finalize', function () {
            console.log('This console log is never being written out.');
});
docx.on ( 'error', function ( err ) {    
            console.log ( err );
});
docx.generate(res);
```

**Comment by Ziv-Barber** [comment]
0.8 not supported anymore.
