### ISSUE TITLE
Returning doc,docx files's proprieties like number of pages

### ISSUE THREAD

**Issue by MakoMakox** [Ziv-Barber/officegen#57]
I want to know if it's possible to be made with officegen or do I need something else. I want to get all files from a folders and return how many pages has each document with names and everything. I need an quick answer so anything will do . Thank you for the support.

**Comment by pietersv** [comment]
officegen is primarily a document generation library.  It sounds like you want to read existing docx file and extract their properties.   On Node.js, you can loop through filenames in a directory, read the files, and count the page breaks:
```js
var JSZip = require('jszip');
var fs = require('fs');
var cheerio = require('cheerio');

fs.readdir(DIRECTORY, function (err, files) {
  files.filter(function (file) {return file.substr(-5).toLowerCase() == ".docx";}).forEach(function (file) {
        fs.readFile(DIRECTORY + file, function (err, content) {
          var zip = new JSZip();
          zip.load(content);
          var xml = zip.file('word/document.xml').asText();
          var $xml = cheerio.load(xml, {xmlMode: true})
          var breaks = $xml('w\\:br[w\\:type="page"]');
          console.log([file, breaks.length])
        });
      })
});
```

**Comment by MakoMakox** [comment]
Thanks it helped me a lot with my research. I tried doing it with .doc files but it doesn't seem to work. I don't want to sound stupid or anything but can you make an example for doc too please. Thank you so much for the support :+1:

**Comment by pietersv** [comment]
Hm, the binary format is tougher.  May be a better topic for StackOverflow,
e.g.
http://stackoverflow.com/questions/9038231/can-i-read-pdf-or-word-docs-with-node-js

On Sat, Apr 11, 2015 at 4:03 PM, MakoMakox <notifications@github.com> wrote:

> Thanks it helped me a lot with my research. I tried doing it with .doc
> files but it doesn't seem to work. I don't want to sound stupid or anything
> but can you make an example for doc too please. Thank you so much for the
> support [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Ziv-Barber/officegen/issues/57#issuecomment-91920275>.
>



-- 
Pieter Sheth-Voss PhD

*protobi*
e: pieter@protobi.com
m: 617.645.4524

**Comment by Jonexuan** [comment]
@MakoMakox hi,I'm a new beginner of web development.I wonder if u have already solve this problem.Could u make an example.Thanks a lot.

**Comment by vishal7201** [comment]
https://www.npmjs.com/package/docx-pdf-pagecount using this module the number of pages in docx and pdf file can be returned.
```
const getPageCount = require('docx-pdf-pagecount');

getPageCount('E:/sample/document/aa/test.docx')
  .then(pages => {
    console.log(pages);
  })
  .catch((err) => {
    console.log(err);
  });
  

getPageCount('E:/sample/document/vb.pdf')
  .then(pages => {
    console.log(pages);
  })
  .catch((err) => {
    console.log(err);
  });
const getPageCount = require('docx-pdf-pagecount');

getPageCount('E:/sample/document/aa/test.docx')
  .then(pages => {
    console.log(pages);
  })
  .catch((err) => {
    console.log(err);
  });
  

getPageCount('E:/sample/document/vb.pdf')
  .then(pages => {
    console.log(pages);
  })
  .catch((err) => {
    console.log(err);
  });
```
