### ISSUE TITLE
The addImage method  example is with wrong paramter

### ISSUE THREAD

**Issue by levi0913** [Ziv-Barber/officegen#58]
pObj.addImage ( path.resolve(__dirname, 'myFile.png' ) ); 
pObj.addImage ( path.resolve(__dirname, 'myFile.png', { cx: 300, cy: 200 } ) );

It should be : 
pObj.addImage ( path.resolve(__dirname, 'myFile.png' ), { cx: 300, cy: 200 } );

**Comment by jinghao1** [comment]
+1
please updade README.md on
https://github.com/Ziv-Barber/officegen/blob/master/manual/docx/README.md

**Comment by jinghao1** [comment]
@Ziv-Barber
