### ISSUE TITLE
How to add a bar chart

### ISSUE THREAD

**Issue by alexleventer** [Ziv-Barber/officegen#62]
How do I add a bar chart? The documentation is very inconsistent, it doesn't look like it's possible to add a barchart w/ the example code, is this correct? `slide.addBarChart(
    { title: 'Sample bar chart',
        data:  [ // each item is one serie
      {
        name: 'europe',
        labels: ['Y2003', 'Y2004', 'Y2005'],
        values: [2.5, 2.6, 2.8],
        color: 'ff0000' // optional
      },
      {
        name: 'namerica',
        labels: ['Y2003', 'Y2004', 'Y2005'],
        values: [2.5, 2.7, 2.9],
        color: '00ff00' // optional
      },
      {
        name: 'asia',
        labels: ['Y2003', 'Y2004', 'Y2005'],
        values: [2.1, 2.2, 2.4],
        color: '0000ff' // optional
      },
      {
        name: 'lamerica',
        labels: ['Y2003', 'Y2004', 'Y2005'],
        values: [0.3, 0.3, 0.3],
        color: 'ffff00' // optional
      },
      {
        name: 'meast',
        labels: ['Y2003', 'Y2004', 'Y2005'],
        values: [0.2, 0.3, 0.3],
        color: 'ff00ff' // optional
      },
      {
        name: 'africa',
        labels: ['Y2003', 'Y2004', 'Y2005'],
        values: [0.1, 0.1, 0.1],
        color: '00ffff' // optional
      }

```
]
}
```

);`

**Comment by pietersv** [comment]
@alexleventer  It is possible to create a bar chart.  See `examples/make_pptx.js` for a few examples.  For your immediate purpose, use the more general `slide.makeChart(..)` and set `renderType: 'bar'` on the object you pass to it:

```js
slide.makeChart({
     title: 'Sample bar chart',
     renderType: 'bar', 
     data: [...]
 });
```

Thanks for catching the issue with the convenience methods. Will fix that and the docs, and  these to the nascent test files

**Comment by pietersv** [comment]
Note the updates to previous example, it's `slide.addChart`

**Comment by alexleventer** [comment]
Thanks for the quick response @pietersv , do I first have to make the chart and then add chart?

**Comment by alexleventer** [comment]
I'm still getting an error on addChart `undefined is not a function`.

**Comment by alexleventer** [comment]
Looks like NPM module is out of date w/ the repo

**Comment by alexleventer** [comment]
and the latest npm release includes `setWidescreen` but this repo does not.

**Comment by pietersv** [comment]
aha. there's an outstanding pull request.  For now try  `npm install pietersv/officegen`.  Below is a complete example that should work.


```js
var fs = require('fs');
var officegen = require('../');
    var chartInfo = {
      title: 'Sample bar chart',
      renderType: 'bar',
      xmlOptions: {
        "c:title": {
          "c:tx": {
            "c:rich": {
              "a:p": {
                "a:r": {
                  "a:t": "Override title via XML"
                }
              }
            }
          }
        }
      },
      data: [
        {
          name: 'europe',
          labels: ['Y2003', 'Y2004', 'Y2005'],
          values: [2.5, 2.6, 2.8],
          color: 'ff0000'
        },
        {
          name: 'namerica',
          labels: ['Y2003', 'Y2004', 'Y2005'],
          values: [2.5, 2.7, 2.9],
          color: '00ff00'
        },
        {
          name: 'asia',
          labels: ['Y2003', 'Y2004', 'Y2005'],
          values: [2.1, 2.2, 2.4],
          color: '0000ff'
        },
        {
          name: 'lamerica',
          labels: ['Y2003', 'Y2004', 'Y2005'],
          values: [0.3, 0.3, 0.3],
          color: 'ffff00'
        },
        {
          name: 'meast',
          labels: ['Y2003', 'Y2004', 'Y2005'],
          values: [0.2, 0.3, 0.3],
          color: 'ff00ff'
        },
        {
          name: 'africa',
          labels: ['Y2003', 'Y2004', 'Y2005'],
          values: [0.1, 0.1, 0.1],
          color: '00ffff'
        }

      ]
    };

    var chartIdx = 3;
    var pptx = officegen('pptx');
    pptx.setDocTitle('Sample PPTX Document');
    var slide = pptx.makeNewSlide();
    slide.name = 'OfficeChart slide';
    slide.back = 'ffffff';

    slide.addChart(
        chartInfo,
        null,
        function () {
          var FILENAME = "test-ppt-chart" + chartIdx + ".pptx";
          var FILENAME_ALT = "test-ppt-chart-" + chartInfo.renderType + ".pptx";
          var out = fs.createWriteStream('/tmp/' + FILENAME_ALT);
          pptx.generate(out, {
            'finalize': function (written) {
              console.log("Done!")
            },
            'error': console.error
          });
        },  console.error);
```

**Comment by pietersv** [comment]
@alexleventer Glad to hear that worked.    I've just updated the fork https://github.com/pietersv/officegen as follows:

* Changed `slide.addChart( info, renderType, success, error)` to `slide.addChart( info, success, error)`
* Dropped convenience methods `addBarChart()`, `addPieChart()` and `addColumnChart()`
* Updated `README.md`, `examples/make_pptx.js` and `test/test_pptx.js` accordingly

The gist is that the renderType (i.e. `bar`, `pie`, `column`, `group-bar`) was specified in two places, either within the `chartInfo` object and/or the arguments to `addChart()`.  Have dropped the latter, so its only specified in the `chartInfo` object now.
