### ISSUE TITLE
generate never exits

### ISSUE THREAD

**Issue by scorpwarp23** [Ziv-Barber/officegen#64]
Hi, I'm using Node 10.38.

When running my code on the dev box, pptx.generate works fine and the output file is generated. 

However on my Ubuntu Server it never really exits. Any reason why this happens?

**Comment by pietersv** [comment]
@scorpwarp23 Does the PPT include embedded charts?

**Comment by scorpwarp23** [comment]
Nope. Just images and text. Funny thing is it works on my Ubuntu desktop.
The moment I run it on a VM it never exits

On Friday, June 19, 2015, Pieter Sheth-Voss <notifications@github.com>
wrote:

> @scorpwarp23 <https://github.com/scorpwarp23> Does the PPT include
> embedded charts?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Ziv-Barber/officegen/issues/64#issuecomment-113498395>
> .
>


-- 
Shrenik Kenia
+91-9820520019

**Comment by pietersv** [comment]
@scorpwarp23  Could you run the following diagnostic? (I don't have an Ubuntu test machine set up yet)
I divided the tests to see if it's generating charts.   

* Clone the repo https://github.com/pietersv/officegen 
* Run `npm test` or test files individually:
  * `mocha test/test-pptx-nocharts.js` 
  * `mocha test/test-pptx-charts.js` 

If it works for the `nocharts` but fails for the `charts` my next question is whether `jar` is on the path, so try `which jar`.   The embedded charts use `jar` to zip the contents of embedded xlsx file.  The fork this is copied from originally required `zip` to be on the path, but Heroku only had `jar`.  A better solution is to use pure-JS lib such as jszip.

**Comment by scorpwarp23** [comment]
Here's the output:

Note, it passed both tests. FYI, my issue is fundamentally the same as
https://github.com/Ziv-Barber/officegen/issues/26. Basically all i see is
an 8KB file. Is one of the libraries you're using using some kind of
command line util that is available on my desktop but on the VM by default?

root@demo:~/Temp/officegen# mocha test/test-pptx-nocharts.js



  PPTX generator

    ✓ creates a presentation with properties and text (346ms)

    ✓ creates slides with shapes (91ms)

    ✓ creates presentation to widescreen (88ms)

    ✓ creates slides with images (403ms)

    ✓ creates a native table (95ms)



  5 passing (1s)


root@demo:~/Temp/officegen# mocha test/test-pptx-charts.js



  PPTX generator

    ✓ creates a slides with charts (261ms)

    ✓ creates a presentation with charts (318ms)

    ✓ creates a presentation with charts (235ms)

    ✓ creates a presentation with charts (236ms)

    ✓ creates a presentation with charts (227ms)

    ✓ creates a presentation with charts (217ms)



  6 passing (2s)

On Fri, Jun 19, 2015 at 7:09 PM, Pieter Sheth-Voss <notifications@github.com
> wrote:

> @scorpwarp23 <https://github.com/scorpwarp23> Could you run the following
> diagnostic? (I don't have an Ubuntu test machine set up yet)
> I divided the tests to see if it's generating charts.
>
>    - Clone the repo https://github.com/pietersv/officegen
>    - Run npm test or test files individually:
>       - mocha test/test-pptx-nocharts.js
>       - mocha test/test-pptx-charts.js
>
> If it works for the nocharts but fails for the charts my next question is
> whether jar is on the path, so try which jar. The embedded charts use jar
> to zip the contents of embedded xlsx file. The fork this is copied from
> originally required zip to be on the path, but Heroku only had jar. A
> better solution is to use pure-JS lib such as jszip.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Ziv-Barber/officegen/issues/64#issuecomment-113517663>
> .
>



-- 
Shrenik Kenia
+91-9820520019

**Comment by pietersv** [comment]
@scorpwarp23  Thanks!  The charts do rely on `jar` being on the path (i.e. the Java Archive tool which creates zip files).  It's possible that it's not finding it.  On terminal type `which jar` and in Node try:
```js
var cmd = 'which jar';
var a = exec(cmd, function(err, stdout, stderr) { console.log(stdout, stderr); })
```

**Comment by pietersv** [comment]
I divided the examples into two files as well:
   * examples/make_pptx.js
   * examples/make_pptx_charts.js

Can you fetch these from the branch and see if one/both work?

**Comment by scorpwarp23** [comment]
Ok I ran this:

var cmd = 'which jar';

var exec = require('child_process').exec;

var a = exec(cmd, function(err, stdout, stderr) { console.log(stdout,
stderr); })


I got /usr/bin/jar

Also as I said before I'm not using charts.


On Fri, Jun 19, 2015 at 8:22 PM, Pieter Sheth-Voss <notifications@github.com
> wrote:

> @scorpwarp23 <https://github.com/scorpwarp23> Thanks! The charts do rely
> on jar being on the path (i.e. the Java Archive tool which creates zip
> files). It's possible that it's not finding it. On terminal type which jar
> and in Node try:
>
> var cmd = 'which jar';var a = exec(cmd, function(err, stdout, stderr) { console.log(stdout, stderr); })
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Ziv-Barber/officegen/issues/64#issuecomment-113536864>
> .
>



-- 
Shrenik Kenia
+91-9820520019

**Comment by pietersv** [comment]
Sincere apologies, I misread that as meaning it was generating just the text and images.

**Comment by scorpwarp23** [comment]
Nah. It's generating a 8KB file. Ok now this is funny. When I run the
example it works fine and generates the powerpoint. However, in my code it
is not working (on the server only, works fine on desktop). Could this be a
RangeError or something?

On Fri, Jun 19, 2015 at 8:32 PM, Pieter Sheth-Voss <notifications@github.com
> wrote:

> Sincere apologies, I misread that as meaning it was generating just the
> text and images.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Ziv-Barber/officegen/issues/64#issuecomment-113540497>
> .
>



-- 
Shrenik Kenia
+91-9820520019

**Comment by scorpwarp23** [comment]
That 8KB file is incomplete. Basically finalise is never reached. I meant
to say the example works on the server as well as the desktop. But my code
does not throw any errors but still generate's finalise event is never
reached. Also could it be something about pptx writing a stream rather than
a buffer. Cause the approximately 8KB file (8006 bytes) makes me think this
is a buffer / stream issue.

On Fri, Jun 19, 2015 at 8:33 PM, Shrenik Kenia <shrenik.kenia@gmail.com>
wrote:

> Nah. It's generating a 8KB file. Ok now this is funny. When I run the
> example it works fine and generates the powerpoint. However, in my code it
> is not working (on the server only, works fine on desktop). Could this be a
> RangeError or something?
>
> On Fri, Jun 19, 2015 at 8:32 PM, Pieter Sheth-Voss <
> notifications@github.com> wrote:
>
>> Sincere apologies, I misread that as meaning it was generating just the
>> text and images.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/Ziv-Barber/officegen/issues/64#issuecomment-113540497>
>> .
>>
>
>
>
> --
> Shrenik Kenia
> +91-9820520019
>



-- 
Shrenik Kenia
+91-9820520019

**Comment by scorpwarp23** [comment]
Hey really sorry for the trouble. So I managed to fix the issue. It was a
bug on my part - was calling the add text method with a variable that was
broken. Strange thing is it never threw me an error. Guess you need an
update there - if add text is passed null or undefined.
