### ISSUE TITLE
npm install fails and chart example don't work

### ISSUE THREAD

**Issue by narendra-agashe** [Ziv-Barber/officegen#80]
This seems to be the most promising library of all. Thanks for the great work.
I am running into some problems when trying this library.

When I try to install officegen module using "npm install protobi/officegen", it doesn't work, throw ENOENT 34 error. so I did npm install officegen that worked and then 
I downloaded zip of the master and merged it with node_modules/officegen. This helped me creating a simple power point with capability for formatting i.e. color/font etc. 
I started using charts but none of the examples worked and I get "ReferenceError:target is not defined" error. I am not sure where am I going wrong..?

I am on nodejs version 0.10.40

Please help.

Regards,
Narendra

**Comment by protobi** [comment]
@narendra-agashe Thanks for reporting. I can install fine with `npm install protobi/officegen`  Can you describe the steps to reproduce the error and the complete error message?  `ENOENT` seems like it's not finding a particular file.  

Another diagostic:
```
cd ~/myprojects
git clone https://github.com/protobi/officegen.git
cd officegen
npm install
npm test
node examples/make_pptx_charts.js 
```

**Comment by narendra-agashe** [comment]
@protobi Thanks a lot for your quick response.
I cloned the repository and installed it successfully.

<b>when i ran npm test, 6 tests failed.

and when i ran node examples/make_pptx_chart.js it thrown an error. (see below)</b>
C:\USER123\Work\experiments\officegen\officegen>node examples/make_pptx_charts.
js

C:\USER123\Work\experiments\officegen\officegen\lib\msexcel-builder.js:875
      return fs.rmdirSync(target);
                          ^
ReferenceError: target is not defined
    at Workbook.cancel (C:\USER123\Work\experiments\officegen\officegen\lib\mse
xcel-builder.js:875:27)
    at C:\USER123\Work\experiments\officegen\officegen\lib\genpptx.js:1557:16
    at C:\USER123\Work\experiments\officegen\officegen\lib\msexcel-builder.js:8
69:18
    at ChildProcess.exithandler (child_process.js:662:7)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5)

C:\USER123\Work\experiments\officegen\officegen>
 
<b> when i ran the npm test, i got below output </b>
C:\USER123\Work\experiments\officegen\officegen>npm test

> officegen@0.2.9 test C:\USER123\Work\experiments\officegen\officegen
> mocha



  DOCX generator
    √ creates a document with text and styles (195ms)
    √ can handle text without spaces (81ms)
    1) creates a document with images

  PPTX generator
    √ creates a slides with charts (134ms)
    2) creates a presentation with charts
    3) creates a presentation with charts
    4) creates a presentation with charts
    5) creates a presentation with charts
    6) creates a presentation with charts

  PPTX generator
    √ creates a presentation with properties and text (87ms)
    √ creates slides with shapes (86ms)
    √ creates presentation to widescreen (108ms)
    √ creates slides with images (350ms)
    √ creates a native table (77ms)

  XLSX generator
    √ creates a spreadsheet with text and numbers (117ms)


  9 passing (2s)
  6 failing

  1) DOCX generator creates a document with images:

      Uncaught AssertionError: false == true
      + expected - actual

      -false
      +true

      at null._onTimeout (C:\USER123\Work\experiments\officegen\officegen\test\
test-docx.js:182:11)

  2) PPTX generator creates a presentation with charts:
     Uncaught ReferenceError: target is not defined
      at Workbook.cancel (C:\USER123\Work\experiments\officegen\officegen\lib\m
sexcel-builder.js:875:27)
      at C:\USER123\Work\experiments\officegen\officegen\lib\genpptx.js:1557:16

      at C:\USER123\Work\experiments\officegen\officegen\lib\msexcel-builder.js
:869:18
      at ChildProcess.exithandler (child_process.js:662:7)
      at maybeClose (child_process.js:766:16)
      at Process.ChildProcess._handle.onexit (child_process.js:833:5)

  3) PPTX generator creates a presentation with charts:
     Uncaught ReferenceError: target is not defined
      at Workbook.cancel (C:\USER123\Work\experiments\officegen\officegen\lib\m
sexcel-builder.js:875:27)
      at C:\USER123\Work\experiments\officegen\officegen\lib\genpptx.js:1557:16

      at C:\USER123\Work\experiments\officegen\officegen\lib\msexcel-builder.js
:869:18
      at ChildProcess.exithandler (child_process.js:662:7)
      at maybeClose (child_process.js:766:16)
      at Process.ChildProcess._handle.onexit (child_process.js:833:5)

  4) PPTX generator creates a presentation with charts:
     Uncaught ReferenceError: target is not defined
      at Workbook.cancel (C:\USER123\Work\experiments\officegen\officegen\lib\m
sexcel-builder.js:875:27)
      at C:\USER123\Work\experiments\officegen\officegen\lib\genpptx.js:1557:16

      at C:\USER123\Work\experiments\officegen\officegen\lib\msexcel-builder.js
:869:18
      at ChildProcess.exithandler (child_process.js:662:7)
      at maybeClose (child_process.js:766:16)
      at Process.ChildProcess._handle.onexit (child_process.js:833:5)

  5) PPTX generator creates a presentation with charts:
     Uncaught ReferenceError: target is not defined
      at Workbook.cancel (C:\USER123\Work\experiments\officegen\officegen\lib\m
sexcel-builder.js:875:27)
      at C:\USER123\Work\experiments\officegen\officegen\lib\genpptx.js:1557:16

      at C:\USER123\Work\experiments\officegen\officegen\lib\msexcel-builder.js
:869:18
      at ChildProcess.exithandler (child_process.js:662:7)
      at maybeClose (child_process.js:766:16)
      at Process.ChildProcess._handle.onexit (child_process.js:833:5)

  6) PPTX generator creates a presentation with charts:
     Uncaught ReferenceError: target is not defined
      at Workbook.cancel (C:\USER123\Work\experiments\officegen\officegen\lib\m
sexcel-builder.js:875:27)
      at C:\USER123\Work\experiments\officegen\officegen\lib\genpptx.js:1557:16

      at C:\USER123\Work\experiments\officegen\officegen\lib\msexcel-builder.js
:869:18
      at ChildProcess.exithandler (child_process.js:662:7)
      at maybeClose (child_process.js:766:16)
      at Process.ChildProcess._handle.onexit (child_process.js:833:5)



npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0


Please let me know, if i am doing something very basic in stupid way. :)

Thanks again!
Regards,
Narendra

**Comment by protobi** [comment]
@narendra-agashe Thanks, looking now.

**Comment by protobi** [comment]
Try removing line ms-excelbuilder:875. It appears that `target` is not defined, generating the error.  This method is never called, and my version of node seems not to complain.  


```js
    Workbook.prototype.cancel = function() {
      return fs.rmdirSync(target);
    };
```

Separately, we've amended [ms-excelbuilder](https://github.com/chuanyi/msexcel-builder) so that it no longer uses the file system and returns a pure JSZip object.  Will merge that back into this project.

**Comment by narendra-agashe** [comment]
Thanks @protobi ..!!
I commented out line 875 from ms-excelbuilder and ran node examples/make_pptx_charts.js, it runs with no issues but i don't see any output anywhere.

<b>I am on windows 7 with NodeJS version 0.10.40</b>

I also noticed that it needs a tmp folder on C:, if the folder doesn't exists then it complains because it can not find that location.

when i ran <b>npm test</b>, it was still failing but now error message is changed.
C:\USER123\Work\experiments\officegen\officegen>npm test

> officegen@0.2.9 test C:\USER123\Work\experiments\officegen\officegen
> mocha



  DOCX generator
    √ creates a document with text and styles (226ms)
    √ can handle text without spaces (82ms)
    1) creates a document with images

  PPTX generator
    √ creates a slides with charts (155ms)
    2) creates a presentation with charts
    3) creates a presentation with charts
    4) creates a presentation with charts
    5) creates a presentation with charts
    6) creates a presentation with charts

  PPTX generator
    √ creates a presentation with properties and text (95ms)
    √ creates slides with shapes (99ms)
    √ creates presentation to widescreen (119ms)
    √ creates slides with images (396ms)
    √ creates a native table (110ms)

  XLSX generator
    √ creates a spreadsheet with text and numbers (105ms)


  9 passing (12s)
  6 failing

  1) DOCX generator creates a document with images:

      Uncaught AssertionError: false == true
      + expected - actual

      -false
      +true

      at null._onTimeout (C:\USER123\Work\experiments\officegen\officegen\test\
test-docx.js:182:11)

  2) PPTX generator creates a presentation with charts:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being call
ed in this test.
      at null.<anonymous> (C:\USER123\Work\experiments\officegen\officegen\node
_modules\mocha\lib\runnable.js:189:19)

  3) PPTX generator creates a presentation with charts:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being call
ed in this test.
      at null.<anonymous> (C:\USER123\Work\experiments\officegen\officegen\node
_modules\mocha\lib\runnable.js:189:19)

  4) PPTX generator creates a presentation with charts:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being call
ed in this test.
      at null.<anonymous> (C:\USER123\Work\experiments\officegen\officegen\node
_modules\mocha\lib\runnable.js:189:19)

  5) PPTX generator creates a presentation with charts:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being call
ed in this test.
      at null.<anonymous> (C:\USER123\Work\experiments\officegen\officegen\node
_modules\mocha\lib\runnable.js:189:19)

  6) PPTX generator creates a presentation with charts:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being call
ed in this test.
      at null.<anonymous> (C:\USER123\Work\experiments\officegen\officegen\node
_modules\mocha\lib\runnable.js:189:19)



npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0

Thanks!
Narendra

**Comment by protobi** [comment]
@narendra-agashe I'm not quite able to replicate your issue with npm version, I'm able to call it fine on my machine, as well as the Ziv-Barber/officegen repo.

The proximate issue you're seeing was because `msexcel-builder` raised an exception when trying to write the Excel files that get embedded into a temp directory.  That generated an error, which then caused `workbook.cancel()` to be called, which showed up a long-hidden bug in that library.

I've pushed up changes to https://github.com/protobi/officegen.  This replaces `msexcel-builder` with a new version that does not use the file system to write/read/delete temporary Excel files but does it in memory using jszip.  

Please try this and tell me how it goes. You may need to delete and re-clone the repo.

Let's move the discussion to the issues page https://github.com/protobi/officegen

**Comment by narendra-agashe** [comment]
@protobi Thanks for pushing the code to repo.

After taking the latest code and compiling it everything works great!! :+1: 
Not sure what was off earlier. I am still exploring.

earlier npm test was failing, right now it ran fine, without any error.

Thanks a lot for your help and making this great piece of work.
