### ISSUE TITLE
Feature request: Adding notes to slides, using existing slide template files

### ISSUE THREAD

**Issue by cclass** [Ziv-Barber/officegen#82]
Adding notes to slides, using existing slide template files

Thanks for putting this together, it's great :)

**Comment by MuslimMunir** [comment]
When this feature is expected?

**Comment by Ziv-Barber** [comment]
I'm working right now on the notes feature.
Slide templates also coming soon.

**Comment by Ziv-Barber** [comment]
The speaker notes support been added.
Slides layout coming soon.
