### ISSUE TITLE
(node) sys is deprecated. Use util instead.

### ISSUE THREAD

**Issue by ghost** [Ziv-Barber/officegen#86]
(node) sys is deprecated. Use util instead.

https://github.com/nodejs/node-v0.x-archive/issues/3577

**Comment by jwerre** [comment]
Easy fix:

https://github.com/Ziv-Barber/officegen/blob/master/lib/basicgen.js#L33

**Comment by grahamnewman** [comment]
Hi community,
Very new to all this from a design background. Can you please explain where (e.g. what file in my project) I paste the above Ziv-Barber code into. I am having a problem with:

pi@picar:/var/www/picar $ node app.js beta=300
(node) sys is deprecated. Use util instead.
Pi Car we server listening on port 8080 visit http://ipaddress:8080/socket.html

Sorry to be a pain and many thanks.

**Comment by tjunghans** [comment]
Hi @Ziv-Barber would it be possible to merge and publish this fix?

**Comment by Ziv-Barber** [comment]
Yes, I will do it later today

**Comment by tjunghans** [comment]
Hi @Ziv-Barber, I deleted my comment as this issue has already been fixed and released in 0.4.0 (I was still on 0.2.9). I got confused because this issue is still open. I think it can be closed now.

Have a good day :-)
