### ISSUE TITLE
Meteor Package

### ISSUE THREAD

**Issue by eliasthompson** [Ziv-Barber/officegen#89]
Not sure if this is still maintained, but is there any chance of this being packaged up for Meteor?

I have a Meteor project right now that has to generate a PowerPoint presentation, and right now the way we're trying to do it is by using the archiver package to try and zip up a bunch of XML files and output it as a pptx file. So far we haven't had a lot of success getting PowerPoint open it, and I still don't know if all the _rels files are necessary and, if they are, how we'd generate them.

I noticed that, in another issue (#18), @StefanVD mentioned he uses this with Meteor, but if he or anyone has any idea how to package this for Meteor or how to go about manually generating a PowerPoint file, any help would be appreciated.

**Comment by Salketer** [comment]
Your best bet would be with the NPM moduls package: https://atmospherejs.com/meteorhacks/npm

This lets you use any NPM module within your meteor app...

**Comment by Ziv-Barber** [comment]
npm install officegen -g
