### ISSUE TITLE
Thanks for word.addImage()! Any chance of word.addTable() / addHTML() ?

### ISSUE THREAD

**Issue by tkristensen** [Ziv-Barber/officegen#9]
Hi Ziv,

I'm already implementing the addimage feature for the system we're using, so thanks!

The ability to add either a table or an HTML fragment containing an HTML table would be amazingly useful to us! Any chance you feel generous enough to implement it?

Thanks again for the addImage() method!

**Comment by gradualstudent** [comment]
+1 for addTable in PPT.

**Comment by nanthak** [comment]
hi,
I have done creating docx with table, the table contains one row with two cells. i can generate a docx and its works. When i open a generated file, cells are exceeding the docx size. Is there any way to use css to modify the table design.
