### ISSUE TITLE
slide.addTable is not a function

### ISSUE THREAD

**Issue by ollywilson** [Ziv-Barber/officegen#90]
Running the example make_pptx.js file is giving 'TypeError: slide.addTable is not a function'

**Comment by pietersv** [comment]
@ollywilson Thanks for reporting that.  Can you provide the error trace, and diagnostic hints (e.g. is it a clean build, what OS, etc.)   I'm able to run it fine from a clean clone of the repo:
```bash
git clone https://github.com/Ziv-Barber/officegen.git
cd officgen
npm install
node examples/make_pptx
open out.pptx
```
Also there is a pending pull request which has more forma mocha test of pptx generation including tables:
```bash
npm install protobi/officegen
cd officegen
npm install 
mocha test/test-pptx-nocharts.js
npm test  # to run all tests
```

**Comment by ollywilson** [comment]
Thanks! Worked with a clean clone. Much appreciated.

**Comment by marti4ka** [comment]
I have the same issue using the latest npm version (0.2.9). The available functions for me are getPageNumber, addText, addShape, addImage, addP and addDateToHeader. When I clone the repository from here, addTable works just fine.
