### ISSUE TITLE
version problem

### ISSUE THREAD

**Issue by japneet121** [Ziv-Barber/officegen#95]
when i npm install the module of officegen-2 i am not able to even run the examples  but if i gitclone this project it works fine ,there are different versions from both the procedures
version with git clone is 0.2.9
and one with npm install is 0.3.7.

**Comment by pietersv** [comment]
@japneet121  `npm officegen-2`  or `npm officegen`?  This project now incorporates PowerPoint charting developed in the separate branch [officegen-2](https://www.npmjs.com/package/officegen-2) and also updates a few aspects, such as how it ZIPs the files.

**Comment by japneet121** [comment]
i used  officegen-2 as when i installed officegen the charting facility was not provided.
i want to use charting in pptx files and want to use a npm install command what shall i do to achieve this purpose.

**Comment by pietersv** [comment]
officegen does have charts. It appears the npm version 0.2.9 matches the repo.  To test
```bash
npm install officegen
cd node_modules/officegen   # or wherever npm installs it to, look at install log
npm install
node make_pptx_charts.js
open out.pptx
```

**Comment by japneet121** [comment]
i installed using npm install offigen@0.2.9
but i didn't get any example files of charts.

**Comment by pietersv** [comment]
@japneet121 Can you provide more diagnostic info?
* What OS / version of node are you running?
* Do you get an error message when running `node examples/make_pptx_charts.js`?
* Does the file `out.pptx` not appear in the project root?
* What result do you see when running the regression test, `mocha test/test-pptx-charts.js`?

```bash
 git clone https://github.com/Ziv-Barber/officegen
cd officegen
npm install
mocha test/test-pptx-charts.js
node examples/make_pptx_charts.js 
open out.pptx
```

**Comment by japneet121** [comment]
i am able to generate  out.pptx file if i git clone the module but if i use npm install for installing officegen the the module that is installed do not contain the examples of charting .
also the lib folder do not contain the officechart.js file. and it seems that module  do not support charting.
error information::


jschawla@li-vishal:~/Desktop/node_modules/officegen/examples$ node make_pptx_charts.js

module.js:340
    throw err;
          ^
Error: Cannot find module '../lib/officechart.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/jschawla/Desktop/node_modules/officegen/examples/make_pptx_charts.js:2:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

**Comment by pietersv** [comment]
@japneet121 Aha, you're exactly right.  The npm is indeed behind the repo.  I see it in a clean clone (there were too many versions of it on my machine) The main repo should increment the version number from 0.29 and republish to npm.
You might try installing from github directly, `npm install Ziv-Barber/officegen --save` until then.

**Comment by japneet121** [comment]
thank you @pietersv

**Comment by Ziv-Barber** [comment]
I'm back and I'm working on a new npm release.
